# Background and foreground colors
background = #020000
foreground = #ffffff

# Standard colors
palette = 0=#020000
palette = 1=#fd0202
palette = 2=#1a9200
palette = 3=#ffff00
palette = 4=#ff0000
palette = 5=#d10a0a
palette = 6=#ff0000
palette = 7=#ffffff

# Bright colors
palette = 8=#630000
palette = 9=#ff0000
palette = 10=#14ff00
palette = 11=#ff0000
palette = 12=#ff0000
palette = 13=#ff0000
palette = 14=#808080
palette = 15=#ffffff
