background            #020000
foreground            #ffffff

# black
color0  #020000
color8  #630000

# red
color1  #fd0202
color9  #ff0000

# green
color2  #1a9200
color10 #14ff00

# yellow
color3  #ffff00
color11 #ff0000

# blue
color4  #ff0000
color12 #ff0000

# magenta
color5  #d10a0a
color13 #ff0000

#cyan
color6  #ff0000
color14 #808080

#white
color7  #ffffff
color15 #ffffff


